[2023-03-09 23:02:14,461] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,472] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,463] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,684] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,462] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,462] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,888] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,462] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,888] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,889] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,889] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,462] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,461] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,888] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,683] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,679] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,890] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:14,893] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:02:16,197] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,198] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,197] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,197] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,216] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,216] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,214] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:16,213] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:02:28,955] INFO [test_snowflake_connector|task-0] 
[SF_KAFKA_CONNECTOR] list stage SNOWFLAKE_KAFKA_CONNECTOR_test_snowflake_connector_STAGE_test_table retrieved 1 file names (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:79)
[2023-03-09 23:02:28,962] WARN [test_snowflake_connector|task-0] Resetting cleaner files SNOWFLAKE_KAFKA_CONNECTOR_test_snowflake_connector_PIPE_test_table_0 done (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:103)
[2023-03-09 23:19:18,465] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,465] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,466] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,466] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,501] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,465] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,465] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,503] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,465] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,503] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,503] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,503] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,502] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,502] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,488] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient:797)
[2023-03-09 23:19:18,466] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,517] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,517] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,466] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,519] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,519] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,503] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,527] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Cancelled in-flight FETCH request with correlation id 20224 due to node 0 being disconnected (elapsed time since creation: 994434ms, elapsed time since send: 994434ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-03-09 23:19:18,528] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,528] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,528] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error sending fetch request (sessionId=740740871, epoch=62) to node 0: (org.apache.kafka.clients.FetchSessionHandler:602)
org.apache.kafka.common.errors.DisconnectException
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,533] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,533] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,530] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:19:18,534] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,534] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,533] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,536] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,533] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,536] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,533] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,536] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,532] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,537] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,532] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,537] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,611] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,644] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:18,890] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:19:18,893] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,893] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,891] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:19:18,891] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:19:18,894] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,894] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,890] WARN [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:19:18,890] WARN [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:19:18,895] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,895] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,894] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,895] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:18,895] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:19:18,895] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:19:20,314] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:20,314] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:20,328] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:20,328] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:19:20,328] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,464] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,464] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,465] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,464] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,513] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,466] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,514] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,514] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,466] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,527] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,466] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,465] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,528] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,465] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,529] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,528] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,528] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,530] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,528] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,525] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,535] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,538] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,525] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,514] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,539] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,544] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,538] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,537] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,544] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,545] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,532] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,529] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:22,545] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,551] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,544] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,552] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,542] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,550] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:22,553] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,554] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,554] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,555] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,606] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:36:22,607] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:36:22,608] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:36:23,373] ERROR [test_snowflake_connector|task-0] Operation timed out (Read failed) (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-09 23:36:24,985] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,989] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,989] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,989] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,989] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,998] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,995] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:24,995] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:36:26,929] ERROR [test_snowflake_connector|task-0] HTTP Status: 401 ErrorBody: {
  "data" : null,
  "code" : "390144",
  "message" : "JWT token is invalid.",
  "success" : false,
  "headers" : null
} (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-09 23:36:29,253] ERROR [test_snowflake_connector|task-0] HTTP Status: 401 ErrorBody: {
  "data" : null,
  "code" : "390144",
  "message" : "JWT token is invalid.",
  "success" : false,
  "headers" : null
} (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-09 23:36:33,538] ERROR [test_snowflake_connector|task-0] HTTP Status: 401 ErrorBody: {
  "data" : null,
  "code" : "390144",
  "message" : "JWT token is invalid.",
  "success" : false,
  "headers" : null
} (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-09 23:36:41,834] ERROR [test_snowflake_connector|task-0] HTTP Status: 401 ErrorBody: {
  "data" : null,
  "code" : "390144",
  "message" : "JWT token is invalid.",
  "success" : false,
  "headers" : null
} (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-09 23:36:41,837] WARN [test_snowflake_connector|task-0] Cleaner encountered an exception class com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:

[SF_KAFKA_CONNECTOR] Exception: Failed to read load history
[SF_KAFKA_CONNECTOR] Error Code: 3002
[SF_KAFKA_CONNECTOR] Detail: Exception reported by Ingest SDK
[SF_KAFKA_CONNECTOR] Message: 
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Exception: Max retry exceeded
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Error Code: 2010
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Detail: Api retry exceeded the max retry limit
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Message: HTTP Status: 401 ErrorBody: {
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "data" : null,
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "code" : "390144",
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "message" : "JWT token is invalid.",
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "success" : false,
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "headers" : null
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] }
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.connection.ServiceResponseHandler.handleExceptionalStatus(ServiceResponseHandler.java:199)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.connection.ServiceResponseHandler.unmarshallHistoryResponse(ServiceResponseHandler.java:127)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.SimpleIngestManager.getHistory(SimpleIngestManager.java:528)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.lambda$readIngestReport$2(SnowflakeIngestionServiceV1.java:122)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.backoffAndRetry(InternalUtils.java:279)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:121)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.lang.Thread.run(Thread.java:748)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:427)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:403)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:390)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.backoffAndRetry(InternalUtils.java:288)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:121)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415)
[SF_KAFKA_CONNECTOR] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[SF_KAFKA_CONNECTOR] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SF_KAFKA_CONNECTOR] java.lang.Thread.run(Thread.java:748)
[com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:427), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:403), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:390), com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:126), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)] (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:103)
[2023-03-09 23:52:52,463] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient:797)
[2023-03-09 23:52:52,464] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,494] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,617] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,620] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,504] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,859] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,504] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,859] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,504] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,504] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,500] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,498] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Cancelled in-flight FETCH request with correlation id 20305 due to node 0 being disconnected (elapsed time since creation: 960634ms, elapsed time since send: 960634ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-03-09 23:52:52,498] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,862] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error sending fetch request (sessionId=711149755, epoch=61) to node 0: (org.apache.kafka.clients.FetchSessionHandler:602)
org.apache.kafka.common.errors.DisconnectException
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,859] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,647] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:52,862] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,860] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,863] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,864] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-09 23:52:52,867] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:513)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:270)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:52:52,867] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:52:52,868] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:52,868] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-09 23:52:52,868] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-09 23:52:52,967] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:52:53,180] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:52:53,538] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-09 23:52:54,167] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,167] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,168] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,167] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,167] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,167] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,177] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,176] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-09 23:52:54,267] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
