[2023-03-10 03:13:24,438] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,440] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,440] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,440] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,486] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,440] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,489] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,438] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,489] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,438] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,490] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,489] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,488] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,486] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,501] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,474] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,514] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,470] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,515] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,513] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,518] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,519] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,512] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,500] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,500] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,520] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,522] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,522] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,490] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,522] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,526] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,520] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,527] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,527] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,520] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,527] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,519] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,527] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,522] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:24,528] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,528] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,528] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,632] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,633] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,633] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,633] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,632] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,636] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:24,850] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:24,853] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,854] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,636] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:24,633] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:24,854] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:513)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:270)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:321)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1450)
[2023-03-10 03:13:24,850] WARN [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:24,856] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: null. isDisconnected: true. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,855] WARN [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:24,858] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,858] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,855] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:513)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:270)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:321)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1450)
[2023-03-10 03:13:24,857] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:24,859] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:24,859] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: null. isDisconnected: true. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:25,341] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient:797)
[2023-03-10 03:13:25,342] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Cancelled in-flight FETCH request with correlation id 20685 due to node 0 being disconnected (elapsed time since creation: 1006808ms, elapsed time since send: 1006808ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-03-10 03:13:25,349] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error sending fetch request (sessionId=1283594196, epoch=71) to node 0: (org.apache.kafka.clients.FetchSessionHandler:602)
org.apache.kafka.common.errors.DisconnectException
[2023-03-10 03:13:25,351] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:13:25,351] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:13:25,352] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:13:25,443] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:25,546] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:25,749] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:13:26,045] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,128] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,158] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,158] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,269] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,273] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:13:26,273] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,442] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,475] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,442] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,477] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,442] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,478] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,477] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,475] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,475] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,480] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,443] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,480] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,480] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,480] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,478] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,480] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:42,483] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,483] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,483] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,483] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,486] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,486] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,482] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,482] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,482] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,482] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,487] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,487] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,487] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,488] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,487] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,488] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,485] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,487] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,489] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,488] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,489] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,608] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,609] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:42,842] WARN [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:42,842] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:42,842] WARN [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:42,842] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:42,843] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,844] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,843] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,844] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,843] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,845] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:42,842] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:42,845] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:43,609] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient:797)
[2023-03-10 03:29:43,609] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Cancelled in-flight FETCH request with correlation id 20755 due to node 0 being disconnected (elapsed time since creation: 949673ms, elapsed time since send: 949673ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-03-10 03:29:43,610] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error sending fetch request (sessionId=1121213884, epoch=55) to node 0: (org.apache.kafka.clients.FetchSessionHandler:602)
org.apache.kafka.common.errors.DisconnectException
[2023-03-10 03:29:43,610] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:29:43,610] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:29:43,610] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:29:43,712] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:43,865] WARN [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:29:44,124] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:44,256] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:44,257] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:44,257] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:44,258] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:29:46,930] WARN [test_snowflake_connector|task-0] Resetting cleaner files SNOWFLAKE_KAFKA_CONNECTOR_test_snowflake_connector_PIPE_test_table_0 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:103)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,470] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,470] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,479] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,479] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,485] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,485] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,430] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,487] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,487] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,476] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,488] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,489] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,431] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,490] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,431] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,491] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,431] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,492] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,492] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,490] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,490] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,493] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,495] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,490] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,496] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,496] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,490] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,487] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,496] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,497] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,494] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,494] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,497] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,498] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,492] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 03:46:58,497] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,500] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,496] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,501] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,499] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,501] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,501] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,637] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,637] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,637] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,638] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,637] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,637] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,638] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,638] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:46:58,834] WARN [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:46:58,835] WARN [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:46:58,835] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:46:58,835] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,835] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,835] WARN [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:46:58,835] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 03:46:58,835] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,836] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,836] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,837] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,836] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,837] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:46:58,835] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 03:46:58,837] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 03:47:00,247] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:47:00,249] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:47:00,249] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:47:00,251] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 03:47:00,249] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
